import {database} from '@/db';
import {accounts,cents,dayAdd,monthAdd,today,validateLines,loanSchedule,balance,profit,forecast,internalFunding,distributionEntitlement,type Workspace,type Line} from '@/lib/finance';
export const dynamic='force-dynamic';
const uid=()=>crypto.randomUUID();
function str(v:any,n=200){if(typeof v!=='string'||!v.trim()||v.length>n)throw Error('راجع الحقول المطلوبة وطول النص.');return v.trim();}
function date(v:any){const s=str(v,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||isNaN(Date.parse(s+'T12:00Z'))||new Date(s+'T12:00Z').toISOString().slice(0,10)!==s)throw Error('تاريخ غير صحيح.');return s;}
function num(v:any,min:number,max:number){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw Error('قيمة رقمية خارج النطاق المسموح.');return n;}
async function snapshot(db:D1Database,owner:string):Promise<Workspace>{const [a,b,c]=await Promise.all([db.prepare('SELECT * FROM records WHERE owner=? ORDER BY created').bind(owner).all(),db.prepare('SELECT * FROM journals WHERE owner=? ORDER BY date DESC,created DESC').bind(owner).all(),db.prepare('SELECT * FROM audit WHERE owner=? ORDER BY created DESC LIMIT 200').bind(owner).all()]);return {records:a.results.map((r:any)=>({...r,data:JSON.parse(r.data)})),journals:b.results.map((r:any)=>({...r,lines:JSON.parse(r.lines)})),audit:c.results};}
function identify(req:Request){const owner=req.headers.get('oai-authenticated-user-id');if(!owner)throw Error('AUTH');return owner;}
export async function GET(req:Request){try{const owner=identify(req);return Response.json(await snapshot(database(),owner),{headers:{'Cache-Control':'no-store'}});}catch(e:any){return Response.json({error:e.message==='AUTH'?'سجل الدخول للوصول إلى بياناتك.':'تعذر تحميل البيانات. حاول مجددًا.'},{status:e.message==='AUTH'?401:503});}}
export async function POST(req:Request){try{const owner=identify(req);if(req.headers.get('sec-fetch-site')==='cross-site')return Response.json({error:'طلب غير مسموح'},{status:403});if(!req.headers.get('content-type')?.includes('application/json'))throw Error('نوع الطلب غير صحيح.');const raw=await req.text();if(raw.length>100000)throw Error('حجم الطلب أكبر من المسموح.');const body=JSON.parse(raw);const action=str(body.action,50),id=str(body.requestId,100),p=body.payload||{};const db=database();if(await db.prepare('SELECT id FROM commands WHERE id=? AND owner=?').bind(id,owner).first())return Response.json({ok:true,replayed:true});const w=await snapshot(db,owner),time=new Date().toISOString();let ops:D1PreparedStatement[]=[];const ledgerLocks=new Map<string,number>();const inserts:{id:string;kind:string;data:string}[]=[];
const patches=new Map<string,{id:string;version:number;data:string}>();
const guardProject=(pid:string)=>{const pr=w.records.find(r=>r.id===pid&&r.kind==='project');if(pr)ledgerLocks.set(pr.id,pr.version);};
const put=(kind:string,data:any,rid=uid())=>{inserts.push({id:rid,kind,data:JSON.stringify(data)});if(data.project)guardProject(data.project);return rid;};
const find=(rid:string,kind?:string)=>{const r=w.records.find(r=>r.id===rid&&(!kind||r.kind===kind));if(!r)throw Error('السجل غير موجود أو غير مسموح.');return r;};
const update=(r:any,data:any)=>{patches.set(r.id,{id:r.id,version:r.version,data:JSON.stringify(data)});if(data.project)guardProject(data.project);};
const project=(rid:string)=>{const r=find(rid,'project');if(r.data.mode==='investment')throw Error('الاستثمار الخارجي يسجل في دفاتر المشروع الممول.');return r;};
const journal=(kind:string,memo:string,d:string,lines:Line[],source:string|null=null,reversal:string|null=null)=>{validateLines(lines);date(d);if(d>today())throw Error('سجل العمليات المستقبلية في الالتزامات، وليس في القيود الفعلية.');for(const l of lines){const pr=project(l.project);ledgerLocks.set(pr.id,pr.version);if(pr.data.closedThrough&&d<=pr.data.closedThrough)throw Error('الفترة مقفلة في هذا المشروع.');}ops.push(db.prepare('INSERT INTO journals(id,owner,date,memo,kind,lines,source,reversal,created) VALUES(?,?,?,?,?,?,?,?,?)').bind(uid(),owner,d,str(memo,500),kind,JSON.stringify(lines),source,reversal,time));};
const pair=(pr:string,debit:string,credit:string,a:number):Line[]=>[{project:pr,account:debit,debit:a,credit:0},{project:pr,account:credit,debit:0,credit:a}];
const due=(data:any,rid=uid())=>put('obligation',{status:'pending',...data},rid);
let description=action;
if(action==='project'){put('project',{name:str(p.name),activity:str(p.activity),mode:['operating','investment'].includes(p.mode)?p.mode:'operating',ownership:num(p.ownership,0.01,100),reserve:cents(p.reserve||0),payout:num(p.payout??30,0,100),partner:p.partner?str(p.partner):'',closedThrough:''});description='إضافة مشروع: '+p.name;}
else if(action==='projectSettings'){const r=find(p.id,'project');if(p.version!==r.version)throw Error('تغيرت البيانات. حدث الصفحة.');update(r,{...r.data,name:str(p.name),reserve:cents(p.reserve),payout:num(p.payout,0,100),partner:p.partner?str(p.partner):''});description='تعديل إعدادات مشروع: '+r.data.name;}
else if(action==='closePeriod'){const r=project(p.id);const d=date(p.date);if(d>today()||d<(r.data.closedThrough||''))throw Error('يمكن فقط إقفال فترة منتهية بعد آخر إقفال.');update(r,{...r.data,closedThrough:d});description='إقفال فترة '+r.data.name+' حتى '+d;}
else if(action==='entry'){const pr=project(p.project),a=cents(p.amount);if(!a)throw Error('المبلغ يجب أن يكون أكبر من صفر.');const mappings:Record<string,string[]>={income:['cash','revenue'],invoice:['receivable','revenue'],collect:['cash','receivable'],expense:['expense','cash'],bill:['expense','payable'],paybill:['payable','cash'],capital:['cash','capital'],asset:['fixed','cash'],inventory:['inventory','cash'],cogs:['cogs','inventory'],depreciation:['depreciation','accumulated'],invest:['investment','cash'],dividend:['cash','dividend'],returnCapital:['cash','investment'],distribution:['distribution','cash']};let lines:Line[]=[];if(p.kind==='transfer'){project(p.target);if(p.target===p.project)throw Error('اختر مشروعين مختلفين.');lines=[...pair(p.project,'inter_receivable','cash',a),...pair(p.target,'cash','inter_payable',a)];}else if(p.kind==='repayTransfer'){project(p.target);if(p.target===p.project)throw Error('اختر مشروعين مختلفين.');if(a>Math.min(internalFunding(w,p.target,p.project,date(p.date)),internalFunding(w,p.target,p.project)))throw Error('المبلغ يتجاوز التمويل المستحق للمشروع المحدد.');lines=[...pair(p.project,'inter_payable','cash',a),...pair(p.target,'cash','inter_receivable',a)];}else if(p.kind==='manual'){if(p.debit===p.credit)throw Error('طرفا القيد يجب أن يكونا مختلفين.');if(['inter_receivable','inter_payable','distribution','loan','investment'].includes(p.debit)||['inter_receivable','inter_payable','distribution','loan','investment'].includes(p.credit))throw Error('لهذه الحسابات استخدم التحويل أو التوزيع أو التمويل أو الاستثمار المخصص لحفظ ترابط السجلات.');lines=pair(p.project,str(p.debit),str(p.credit),a);}else{if(!mappings[p.kind])throw Error('نوع حركة غير معروف.');lines=pair(p.project,mappings[p.kind][0],mappings[p.kind][1],a);}if(p.kind==='distribution'){if(date(p.date)!==today())throw Error('توزيع الأرباح متاح بتاريخ اليوم لضمان فحص السيولة الحالية.');const entitlement=distributionEntitlement(w,pr);const f=forecast(w,p.project,pr.data.reserve,0,0,a);if(a>entitlement||f.min<pr.data.reserve)throw Error('السحب يتجاوز استحقاق المالك أو ينزل السيولة المتوقعة تحت الاحتياطي. راجع مركز القرار.');}if(['invest','dividend','returnCapital'].includes(p.kind)){find(p.investment,'project');if(find(p.investment).data.mode!=='investment')throw Error('اختر استثمارًا خارجيًا.');if(p.kind==='returnCapital'){const invested=w.journals.filter(j=>j.source?.startsWith('investment:'+p.investment+':')).flatMap(j=>j.lines).filter(l=>l.project===p.project&&l.account==='investment').reduce((s,l)=>s+l.debit-l.credit,0);if(a>invested)throw Error('الاسترداد يتجاوز رأس المال المسجل لهذا الاستثمار.');}}journal(p.kind,str(p.memo,500),date(p.date),lines,p.investment?'investment:'+p.investment+':'+id:null);description='تسجيل حركة مالية: '+p.memo;}
else if(action==='reverse'){const j=w.journals.find(x=>x.id===p.id);if(!j||j.reversal||j.source)throw Error('يمكن عكس القيود المباشرة فقط. القيود المرتبطة بالتزامات تحتاج تسوية مخصصة.');if(w.journals.some(x=>x.reversal===j.id))throw Error('تم عكس هذا القيد بالفعل.');journal('reversal','عكس: '+j.memo+' — '+str(p.reason,200),date(p.date),j.lines.map(l=>({...l,debit:l.credit,credit:l.debit})),null,j.id);description='عكس قيد مع الاحتفاظ بالأصل';}
else if(action==='obligation'){project(p.project);const a=cents(p.amount);if(!a)throw Error('أدخل مبلغًا أكبر من صفر.');const start=date(p.date),count=Math.trunc(num(p.count||1,1,365)),repeat=p.repeat||'once';if(!['once','daily','monthly','yearly'].includes(repeat))throw Error('تكرار غير صحيح.');if(!['in','out'].includes(p.direction))throw Error('حدد اتجاه الحركة.');const category=str(p.category);if(!accounts[category]||['cash','inter_receivable','inter_payable','loan','investment','distribution'].includes(category))throw Error('اختر حسابًا مقابلًا صالحًا.');for(let i=0;i<(repeat==='once'?1:count);i++){due({project:p.project,title:str(p.title),amount:a,date:repeat==='daily'?dayAdd(start,i):monthAdd(start,repeat==='yearly'?i*12:i),direction:p.direction,category,certainty:num(p.certainty??100,0,100)});}description='جدولة: '+p.title;}
else if(action==='settle'){const r=find(p.id,'obligation'),d=r.data;if(d.status!=='pending')throw Error('الاستحقاق تمت معالجته بالفعل.');const dt=date(p.date);let lines:Line[];if(d.loan){lines=[...(d.principal?[{project:d.project,account:'loan',debit:d.principal,credit:0}]:[]),...(d.interest?[{project:d.project,account:'interest',debit:d.interest,credit:0}]:[]),{project:d.project,account:'cash',debit:0,credit:d.amount}];}else lines=pair(d.project,d.direction==='in'?'cash':d.category,d.direction==='in'?d.category:'cash',d.amount);journal('settle',d.title,dt,lines,'obligation:'+r.id);update(r,{...d,status:'paid',paidOn:dt});description='تسوية استحقاق: '+d.title;}
else if(action==='cancelDue'){const r=find(p.id,'obligation');if(r.data.status!=='pending'||r.data.loan)throw Error('هذا الاستحقاق لا يمكن إلغاؤه من هنا.');update(r,{...r.data,status:'cancelled',reason:str(p.reason)});description='إلغاء استحقاق: '+r.data.title;}
else if(action==='employee'){project(p.project);const salary=cents(p.salary),start=date(p.firstDate),count=Math.trunc(num(p.months??12,1,24));if(!salary)throw Error('أدخل راتبًا أكبر من صفر.');const rid=put('employee',{name:str(p.name),job:str(p.job),project:p.project,salary,firstDate:start,months:count,status:'active'});for(let i=0;i<count;i++)due({project:p.project,title:'راتب '+p.name,amount:salary,date:monthAdd(start,i),direction:'out',category:'salary',employee:rid,certainty:100});description='إضافة موظف وجدولة راتبه: '+p.name;}
else if(action==='renewPayroll'){
 const r=find(p.id,'employee');if(r.data.status!=='active')throw Error('الموظف غير نشط.');
 const count=num(p.months,1,24);if(!Number.isInteger(count))throw Error('أدخل عدد أشهر صحيحًا.');
 const previous=w.records.filter(o=>o.kind==='obligation'&&o.data.employee===r.id).map(o=>o.data.date).sort().at(-1);
 const salary=cents(p.salary);if(!salary)throw Error('أدخل راتبًا أكبر من صفر.');
 let offset=0;while(previous&&monthAdd(r.data.firstDate,offset)<=previous){offset++;if(offset>1200)throw Error('راجع فترة جدولة الموظف.');}
 const start=monthAdd(r.data.firstDate,offset);
 for(let i=0;i<count;i++)due({project:r.data.project,title:'راتب '+r.data.name,amount:salary,date:monthAdd(r.data.firstDate,offset+i),direction:'out',category:'salary',employee:r.id,certainty:100});
 update(r,{...r.data,salary,scheduledThrough:monthAdd(r.data.firstDate,offset+count-1)});
 description='تجديد رواتب '+r.data.name+' بدءًا من '+start;
}
else if(action==='stopEmployee'){const r=find(p.id,'employee'),from=date(p.date);update(r,{...r.data,status:'stopped',endDate:from});for(const o of w.records.filter(o=>o.kind==='obligation'&&o.data.employee===r.id&&o.data.status==='pending'&&o.data.date>=from))update(o,{...o.data,status:'cancelled',reason:'إيقاف الموظف'});description='إيقاف استحقاقات موظف: '+r.data.name;}
else if(action==='loan'){project(p.project);const amount=cents(p.amount),start=date(p.start),first=date(p.firstDate),annual=num(p.rate,0,100),months=Math.trunc(num(p.months,1,360));if(first<start)throw Error('أول قسط يجب أن يكون بعد استلام التمويل.');const rid=put('loan',{project:p.project,name:str(p.name),principal:amount,rate:annual,months,start,firstDate:first,scheduleType:'estimate',fundingMode:p.fundingMode==='opening'?'opening':'new'});const schedule=loanSchedule(amount,annual,months,first);for(const [i,s]of schedule.entries())due({...s,project:p.project,title:'قسط '+p.name+' / '+(i+1),direction:'out',category:'loan',loan:rid,certainty:100});journal('loan',(p.fundingMode==='opening'?'رصيد تمويل افتتاحي: ':'استلام تمويل: ')+p.name,start,pair(p.project,p.fundingMode==='opening'?'capital':'cash','loan',amount),'loan:'+rid);description='إضافة تمويل وجدوله التقديري';}
else if(action==='replaceSchedule'){const r=find(p.id,'loan'),d=r.data;const pending=w.records.filter(x=>x.kind==='obligation'&&x.data.loan===r.id&&x.data.status==='pending');const remaining=pending.reduce((s,x)=>s+x.data.principal,0),prepay=cents(p.prepay||0),fee=cents(p.fee||0),dt=date(p.date);if(dt>today())throw Error('تاريخ الاعتماد لا يمكن أن يكون مستقبليًا.');if(prepay>remaining)throw Error('السداد أكبر من أصل الدين المتبقي.');const rows=(p.rows||'').trim()?str(p.rows,30000).split('\n').map((line:string)=>{const [dateStr,pr,it]=line.trim().split(',');return {date:date(dateStr),principal:cents(pr),interest:cents(it)};}):[];if(rows.length>360)throw Error('الحد الأقصى 360 قسطًا.');if(rows.some((s:any,i:number)=>s.date<dt||s.principal+s.interest<=0||(i>0&&s.date<=rows[i-1].date)))throw Error('تواريخ الأقساط يجب أن تكون متزايدة وبعد تاريخ التسوية.');if(rows.reduce((s:number,x:any)=>s+x.principal,0)!==remaining-prepay)throw Error('مجموع أصل الأقساط الجديدة لا يساوي الرصيد المتبقي بعد السداد.');update(r,{...d,scheduleType:'confirmed',revisedOn:dt});for(const o of pending)update(o,{...o.data,status:'replaced'});for(const [i,s]of rows.entries())due({...s,amount:s.principal+s.interest,project:d.project,title:'قسط '+d.name+' / '+(i+1),direction:'out',category:'loan',loan:r.id,certainty:100});if(prepay+fee>0){journal('prepay','سداد مبكر: '+d.name,dt,[...(prepay?[{project:d.project,account:'loan',debit:prepay,credit:0}]:[]),...(fee?[{project:d.project,account:'interest',debit:fee,credit:0}]:[]),{project:d.project,account:'cash',debit:0,credit:prepay+fee}],'prepay:'+id);}description='اعتماد جدول البنك وتسجيل السداد المبكر';}
else if(action==='risk'){if(p.project!=='all')find(p.project,'project');put('risk',{project:p.project,title:str(p.title),likelihood:num(p.likelihood,1,5),impact:num(p.impact,1,5),control:str(p.control,1000),responsible:str(p.responsible),reviewDate:date(p.reviewDate),status:'open'});description='إضافة خطر: '+p.title;}
else if(action==='resolveRisk'){const r=find(p.id,'risk');update(r,{...r.data,status:'resolved',resolution:str(p.resolution,500),resolvedOn:today()});description='توثيق معالجة خطر';}
else throw Error('عملية غير معروفة.');
// Bound JSON keeps SQL and parameter counts small even for a 360-month loan.
if(inserts.length)ops.push(db.prepare("INSERT INTO records(id,owner,kind,data,created) SELECT json_extract(value,'$.id'),?,json_extract(value,'$.kind'),json_extract(value,'$.data'),? FROM json_each(?)").bind(owner,time,JSON.stringify(inserts)));
if(patches.size){
 ops.push(db.prepare("UPDATE records SET data=json_extract(patch.value,'$.data'),version=records.version+1 FROM json_each(?) AS patch WHERE records.id=json_extract(patch.value,'$.id') AND records.owner=? AND records.version=json_extract(patch.value,'$.version')").bind(JSON.stringify([...patches.values()]),owner));
 ops.push(db.prepare("SELECT json(CASE WHEN changes()=? THEN 'true' ELSE 'conflict' END)").bind(patches.size));
}
for(const [pid,version]of ledgerLocks){ops.push(db.prepare('UPDATE records SET version=version+1 WHERE id=? AND owner=? AND version=?').bind(pid,owner,version));ops.push(db.prepare("SELECT json(CASE WHEN changes()=1 THEN 'true' ELSE 'conflict' END)"));}
ops.push(db.prepare('INSERT INTO audit(id,owner,action,detail,created) VALUES(?,?,?,?,?)').bind(uid(),owner,action,req.headers.get('oai-authenticated-user-email')?description+' — '+req.headers.get('oai-authenticated-user-email'):description,time));ops.push(db.prepare('INSERT INTO commands(id,owner,created) VALUES(?,?,?)').bind(id,owner,time));try{await db.batch(ops);}catch(e:any){if(await db.prepare('SELECT id FROM commands WHERE id=? AND owner=?').bind(id,owner).first())return Response.json({ok:true,replayed:true});if(/UNIQUE|malformed JSON/.test(e.message))throw Error('تغيرت البيانات أو تم تسجيل العملية مسبقًا. حدث الصفحة.');throw e;}return Response.json({ok:true});
}catch(e:any){console.error('workspace operation:',e.message);return Response.json({error:e.message==='AUTH'?'سجل الدخول أولًا.':(/D1|SQLITE|syntax|no such/.test(e.message)?'تعذر حفظ العملية. لم يتم اعتمادها. حاول مجددًا.':e.message||'تعذر حفظ العملية.')},{status:e.message==='AUTH'?401:400});}}
